/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestaocpc.visao;

/**
 *
 * @author Viviane Alves
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCadPessoa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        btCadPessoa.setBackground(java.awt.SystemColor.controlHighlight);
        btCadPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestaocpc/visao/imagens/user64.png"))); // NOI18N
        btCadPessoa.setToolTipText("Pessoa");
        btCadPessoa.setBorder(null);
        btCadPessoa.setBorderPainted(false);
        btCadPessoa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCadPessoa.setFocusCycleRoot(true);
        btCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(btCadPessoa);
        btCadPessoa.setBounds(0, 0, 98, 97);

        jButton2.setBackground(java.awt.SystemColor.controlHighlight);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestaocpc/visao/imagens/notepad.png"))); // NOI18N
        jButton2.setToolTipText("Certames");
        jButton2.setBorder(null);
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 0, 98, 97);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 620, 100);

        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(-20, 200, 0, 0);

        setBounds(0, 0, 670, 386);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadPessoaActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        args[0]= "Cadastro de Pessoa";
        pessoaVisao.main(args);
    }//GEN-LAST:event_btCadPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadPessoa;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
